### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/docs-and-discussions#5]
- [x] set up Cognito account for all Klimapartner users
- [x] set up AWS account for Juliane
- [x] set up weekly YSWS update for Juliane (lambda triggered by weekly SNS pub). Should hit YSWS API to get inventory for all products at YSWS. Should also provide buying price of each products by querying our DB (ask Valentin for prices). When all data is serialized and sanitized, post to SNS where Juliane can subscribe
- [x] make stock webhook to update stocks in DB
- [ ] port current YSWS to AWS. This should include logging like `kaskadi` project but shouldn't be included into `kaskadi` since we want to modify architecture. This should be a standalone app for now
- [x] rewrite git pull automation in Klimapartner repo to node CLI utility
- [x] in template + currently deployed resources:
  - [x] change `region` field in `serverless` to just `eu-central-1`
  - [x] default deployment bucket instead of using an environment variable
  - [x] remove `deploymentPrefix` in config files (delete the existing folder before to avoid conflict)
  - [x] switch all runtimes to node12 (Lambdas/API)
- [x] port standalone APIs (like `webhooks`, `stocks`) to the new API template. For the ERP, this will be done when we move the whole infra to the new architecture
- [x] update standalone lambdas to follow the new `template-kaskadi-lambda` (there was some back and forth with layer usage, just align everything)

**Comment by alexlemaire** [comment]
AWS account for Juliane set up. Waiting on her feedback if there are any issues.

**Comment by alexlemaire** [comment]
**Weekly stock update:**

First version is in place.
I left myself subscribed to the topic for now to check that everything works fine.

It should notify Juliane every Monday at 7AM of the stocks.

For now it only fetches from YSWS, updates the stocks in our DB and send a notification for the associated topic (to which she is subscribed).
In the future it should also fetch from other platform.

Will probably still require some optimization and rewriting.

**Comment by alexlemaire** [comment]
@Holger-Will in YSWS there is a product with the external ID `test00001`. I checked if it was possible for me to delete the product through Wemalo API but it doesn't seem so... If you think you don't need it anymore, could you please reach out to them to ask them to erase it from their DB?

With this product on their side I need to do 1 more request per product when I check for buying prices of products in stock to make sure that the product exists in our DB. But I think the data set that YSWS has should be a sub set of ours so I could get rid of this check and make the lambda faster/cheaper if we update this

**Comment by alexlemaire** [comment]
Updated all runtimes to Node12 + hardcoded all regions to `eu-central-1` + removed `deploymentPrefix` from serverless config file and defaulted all `deploymentBucket`

**Comment by alexlemaire** [comment]
Late update on this: all tasks has been done since then except the port of YSWS client to AWS since we won't work with YSWS at the end.

Closing this now.
